# Generated by Django 6.0.5 on 2026-05-30 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0002_seed_predefined_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantCategoryMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("normalized_merchant", models.CharField(max_length=200)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="merchant_mappings", to="categories.category")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="merchant_mappings", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "normalized_merchant")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("booking_date", models.DateField(blank=True, null=True)),
                ("merchant", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=500)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction_number", models.CharField(blank=True, max_length=50)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transactions", to="categories.category")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-date", "-id"],
                "unique_together": {("user", "date", "amount", "merchant", "transaction_number")},
            },
        ),
    ]
