# Generated by Django 6.0.5 on 2026-06-16 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_seed_predefined_categories"),
        ("transactions", "0004_transaction_transaction_user_id_8af7f1_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user", "category", "-date"], name="transaction_user_id_c1e6a9_idx"),
        ),
    ]
