# Generated by Django 6.0.5 on 2026-05-30 15:03

from django.db import migrations

PREDEFINED_CATEGORIES = [
    "Groceries",
    "Transport",
    "Entertainment",
    "Bills",
    "Health",
]


def seed_categories(apps, schema_editor):
    """Create predefined categories for all existing users."""
    User = apps.get_model("auth", "User")
    Category = apps.get_model("categories", "Category")

    categories_to_create = []
    for user in User.objects.all():
        for name in PREDEFINED_CATEGORIES:
            categories_to_create.append(Category(name=name, user=user))

    Category.objects.bulk_create(categories_to_create, ignore_conflicts=True)


def remove_categories(apps, schema_editor):  # noqa: ARG001
    """Reverse migration is a no-op to avoid deleting user data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
