# Generated by Django 6.0.5 on 2026-06-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_seed_predefined_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default="#6c757d", max_length=7, null=True),
        ),
    ]
