# Generated by Django 6.0.5 on 2026-06-17 12:58

from django.db import migrations, models

from categories.colors import color_for_category_name
from categories.signals import PREDEFINED_CATEGORIES


def _backfill_category_color(apps, schema_editor) -> None:
    category_model = apps.get_model("categories", "Category")
    pending = []

    for category in category_model.objects.all().iterator():
        computed = color_for_category_name(category.name, PREDEFINED_CATEGORIES)
        if category.color == computed:
            continue
        category.color = computed
        pending.append(category)

    if pending:
        category_model.objects.bulk_update(pending, ["color"], batch_size=500)


def _noop_reverse(apps, schema_editor) -> None:
    return


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_seed_unknown_category"),
        ("categories", "0003_category_color"),
    ]

    operations = [
        migrations.RunPython(_backfill_category_color, _noop_reverse),
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(default="#6c757d", max_length=7),
        ),
    ]
