# Generated by Django 6.0.5 on 2026-08-31 17:22
"""Introduce the one-level category hierarchy. Forward-only — do not reverse.

Reversing this migration is unsafe on any database that already holds subcategories:

1. Restoring ``unique_together = ("name", "user")`` raises ``IntegrityError`` as soon as a
   subcategory reuses a top-level name, which the new constraints deliberately permit.
2. ``RemoveField("parent")`` silently discards every parent link, flattening the hierarchy
   with no way to reconstruct it.

To undo the feature, write a new forward migration that first reparents or renames the
affected rows.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0004_backfill_category_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="categories.category",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("name", "user"),
                name="unique_top_level_category_name_per_user",
                violation_error_message="You already have a top-level category with this name.",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name", "user", "parent"),
                name="unique_subcategory_name_per_parent",
                violation_error_message="This parent category already has a subcategory with this name.",
            ),
        ),
    ]
